# -*- coding: UTF-8 -*-
from dots_and_boxes.dots_and_boxes import DotsAndBoxes, Player, Color
from dots_and_boxes.main_window_controller import MainWindowController

import sys
from PyQt5.QtWidgets import QApplication


if __name__ == '__main__':
    app = QApplication(sys.argv)
    main_window_controller = MainWindowController()
    main_window_controller.window.show()

    sys.exit(app.exec_())
    db = DotsAndBoxes()
    db.red_player = Player.RedPlayer("player1")
    db.blue_player = Player.BluePlayer("player2")
    db.new_game()
    db.move_with_str("R(b1,v)")
    db.move_with_str("B(f3,v)")
    db.move_with_str("R(a2,h)")
    print(db.last_move)
    db.back()
    print(db.history)
    print(db.last_move)
    db.turn_to_step(3)
    print(db.last_move)
    db.move_with_str("B(a2,v)")
    db.move_with_str("R(a3,h)")
    db.move_with_str("B(b2,v)")
    db.move_with_str("B(f4,v)")
    db.move_with_str("R(c1,v)")
    db.move_with_str("B(e5,h)")
    db.move_with_str("R(c2,v)")
    db.move_with_str("B(d6,h)")
    db.move_with_str("R(e5,v)")
    db.move_with_str("B(a3,v)")
    db.move_with_str("R(a4,v)")
    db.move_with_str("B(a5,h)")
    db.move_with_str("R(e3,v)")
    db.move_with_str("B(c2,h)")
    db.move_with_str("R(d2,h)")
    db.move_with_str("B(b5,v)")
    db.move_with_str("R(e2,v)")
    db.move_with_str("B(c3,v)")
    db.move_with_str("R(d3,v)")
    db.move_with_str("B(e4,h)")
    db.move_with_str("R(e3,h)")
    db.move_with_str("R(e4,v)")
    db.move_with_str("R(f1,v)")
    db.move_with_str("B(d4,v)")
    db.move_with_str("R(c4,v)")
    db.move_with_str("B(b4,h)")
    db.move_with_str("R(c6,h)")
    db.move_with_str("B(a6,h)")
    db.move_with_str("R(d1,h)")
    db.move_with_str("B(a5,v)")
    db.move_with_str("B(d1,v)")
    db.move_with_str("R(c1,h)")
    db.move_with_str("R(e6,h)")
    db.move_with_str("B(e1,v)")
    db.move_with_str("B(f5,v)")
    db.move_with_str("B(b6,h)")
    db.move_with_str("R(f2,v)")
    db.move_with_str("B(e2,h)")
    db.move_with_str("B(e1,h)")
    db.move_with_str("B(a1,h)")
    db.move_with_str("R(a1,v)")
    db.move_with_str("R(d3,h)")
    db.move_with_str("B(d2,v)")
    db.move_with_str("B(c3,h)")
    db.move_with_str("B(c4,h)")
    db.move_with_str("B(c5,h)")
    db.move_with_str("B(d4,h)")
    db.move_with_str("B(d5,h)")
    db.move_with_str("B(d5,v)")
    db.move_with_str("B(c5,v)")
    db.move_with_str("B(b5,h)")
    db.move_with_str("B(b4,v)")
    db.move_with_str("B(a4,h)")
    db.move_with_str("B(b3,v)")
    db.move_with_str("B(b3,h)")
    db.move_with_str("B(b2,h)")
    db.move_with_str("B(b1,h)")
    print(db.save_to_file("/home/ubuntu/",0,""))
    print(db._current_game.winner) #'''

