# -*- coding: UTF-8 -*-
from dots_and_boxes.dots_and_boxes import DotsAndBoxes


if __name__ == '__main__':
    # DotsAndBoxes().run()
    db = DotsAndBoxes()
    db.new_game()
    db.move("R(b1,v)")
    db.move("B(f3,v)")
    db.move("R(a2,h)")
    db.move("B(a2,v)")
    db.move("R(a3,h)")
    db.move("B(b2,v)")
    db.move("B(f4,v)")
    db.move("R(c1,v)")
    db.move("B(e5,h)")
    db.move("R(c2,v)")
    db.move("B(d6,h)")
    db.move("R(e5,v)")
    db.move("B(a3,v)")
    db.move("R(a4,v)")
    db.move("B(a5,h)")
    db.move("R(e3,v)")
    db.move("B(c2,h)")
    db.move("R(d2,h)")
    db.move("B(b5,v)")
    db.move("R(e2,v)")
    db.move("B(c3,v)")
    db.move("R(d3,v)")
    db.move("B(e4,h)")
    db.move("R(e3,h)")
    db.move("R(e4,v)")
    db.move("R(f1,v)")
    db.move("B(d4,v)")
    db.move("R(c4,v)")
    db.move("B(b4,h)")
    db.move("R(c6,h)")
    db.move("B(a6,h)")
    db.move("R(d1,h)")
    db.move("B(a5,v)")
    db.move("B(d1,v)")
    db.move("R(c1,h)")
    db.move("R(e6,h)")
    db.move("B(e1,v)")
    db.move("B(f5,v)")
    db.move("B(b6,h)")
    db.move("R(f2,v)")
    db.move("B(e2,h)")
    db.move("B(e1,h)")
    db.move("B(a1,h)")
    db.move("R(a1,v)")
    db.move("R(d3,h)")
    db.move("B(d2,v)")
    db.move("B(c3,h)")
    db.move("B(c4,h)")
    db.move("B(c5,h)")
    db.move("B(d4,h)")
    db.move("B(d5,h)")
    db.move("B(d5,v)")
    db.move("B(c5,v)")
    db.move("B(b5,h)")
    db.move("B(b4,v)")
    db.move("B(a4,h)")
    db.move("B(b3,v)")
    db.move("B(b3,h)")
    db.move("B(b2,h)")
    db.move("B(b1,h)")
    print(db._current_game.winner)

