# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from .model import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(727, 548)
        MainWindow.setWindowFlags(QtCore.Qt.WindowCloseButtonHint);
        MainWindow.setFixedSize(MainWindow.width(), MainWindow.height());
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(8, 0, 711, 511))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setContentsMargins(0, -1, -1, -1)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.columnView_5 = QtWidgets.QColumnView(self.verticalLayoutWidget)
        self.columnView_5.setMinimumSize(QtCore.QSize(80, 80))
        self.columnView_5.setMaximumSize(QtCore.QSize(80, 80))
        self.columnView_5.setObjectName("columnView_5")
        self.gridLayout_2.addWidget(self.columnView_5, 2, 10, 1, 1)
        self.columnView_16 = QtWidgets.QColumnView(self.verticalLayoutWidget)
        self.columnView_16.setMinimumSize(QtCore.QSize(80, 80))
        self.columnView_16.setMaximumSize(QtCore.QSize(80, 80))
        self.columnView_16.setObjectName("columnView_16")
        self.gridLayout_2.addWidget(self.columnView_16, 8, 8, 1, 1)
        self.columnView_19 = QtWidgets.QColumnView(self.verticalLayoutWidget)
        self.columnView_19.setMinimumSize(QtCore.QSize(80, 80))
        self.columnView_19.setMaximumSize(QtCore.QSize(80, 80))
        self.columnView_19.setObjectName("columnView_19")
        self.gridLayout_2.addWidget(self.columnView_19, 4, 8, 1, 1)
        self.columnView_2 = QtWidgets.QColumnView(self.verticalLayoutWidget)
        self.columnView_2.setMinimumSize(QtCore.QSize(80, 80))
        self.columnView_2.setMaximumSize(QtCore.QSize(80, 80))
        self.columnView_2.setObjectName("columnView_2")
        self.gridLayout_2.addWidget(self.columnView_2, 2, 4, 1, 1)
        self.columnView_24 = QtWidgets.QColumnView(self.verticalLayoutWidget)
        self.columnView_24.setMinimumSize(QtCore.QSize(80, 80))
        self.columnView_24.setMaximumSize(QtCore.QSize(80, 80))
        self.columnView_24.setObjectName("columnView_24")
        self.gridLayout_2.addWidget(self.columnView_24, 10, 10, 1, 1)
        self.columnView_25 = QtWidgets.QColumnView(self.verticalLayoutWidget)
        self.columnView_25.setMinimumSize(QtCore.QSize(80, 80))
        self.columnView_25.setMaximumSize(QtCore.QSize(80, 80))
        self.columnView_25.setObjectName("columnView_25")
        self.gridLayout_2.addWidget(self.columnView_25, 10, 8, 1, 1)
        self.columnView_18 = QtWidgets.QColumnView(self.verticalLayoutWidget)
        self.columnView_18.setMinimumSize(QtCore.QSize(80, 80))
        self.columnView_18.setMaximumSize(QtCore.QSize(80, 80))
        self.columnView_18.setObjectName("columnView_18")
        self.gridLayout_2.addWidget(self.columnView_18, 4, 6, 1, 1)
        self.columnView_9 = QtWidgets.QColumnView(self.verticalLayoutWidget)
        self.columnView_9.setMinimumSize(QtCore.QSize(80, 80))
        self.columnView_9.setMaximumSize(QtCore.QSize(80, 80))
        self.columnView_9.setObjectName("columnView_9")
        self.gridLayout_2.addWidget(self.columnView_9, 10, 2, 1, 1)
        self.columnView_6 = QtWidgets.QColumnView(self.verticalLayoutWidget)
        self.columnView_6.setMinimumSize(QtCore.QSize(80, 80))
        self.columnView_6.setMaximumSize(QtCore.QSize(80, 80))
        self.columnView_6.setObjectName("columnView_6")
        self.gridLayout_2.addWidget(self.columnView_6, 4, 2, 1, 1)
        self.columnView_14 = QtWidgets.QColumnView(self.verticalLayoutWidget)
        self.columnView_14.setMinimumSize(QtCore.QSize(80, 80))
        self.columnView_14.setMaximumSize(QtCore.QSize(80, 80))
        self.columnView_14.setObjectName("columnView_14")
        self.gridLayout_2.addWidget(self.columnView_14, 10, 6, 1, 1)
        self.columnView = QtWidgets.QColumnView(self.verticalLayoutWidget)
        self.columnView.setMinimumSize(QtCore.QSize(80, 80))
        self.columnView.setMaximumSize(QtCore.QSize(80, 80))
        self.columnView.setObjectName("columnView")
        self.gridLayout_2.addWidget(self.columnView, 2, 2, 1, 1)
        self.label1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label1.setFont(font)
        self.label1.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label1.setObjectName("label1")
        self.gridLayout_2.addWidget(self.label1, 10, 0, 2, 1)
        self.label6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label6.setFont(font)
        self.label6.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label6.setObjectName("label6")
        self.gridLayout_2.addWidget(self.label6, 0, 0, 2, 1)
        self.columnView_15 = QtWidgets.QColumnView(self.verticalLayoutWidget)
        self.columnView_15.setMinimumSize(QtCore.QSize(80, 80))
        self.columnView_15.setMaximumSize(QtCore.QSize(80, 80))
        self.columnView_15.setObjectName("columnView_15")
        self.gridLayout_2.addWidget(self.columnView_15, 8, 6, 1, 1)
        self.labelD = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelD.setFont(font)
        self.labelD.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelD.setObjectName("labelD")
        self.gridLayout_2.addWidget(self.labelD, 12, 7, 1, 2)
        self.columnView_4 = QtWidgets.QColumnView(self.verticalLayoutWidget)
        self.columnView_4.setMinimumSize(QtCore.QSize(80, 80))
        self.columnView_4.setMaximumSize(QtCore.QSize(80, 80))
        self.columnView_4.setObjectName("columnView_4")
        self.gridLayout_2.addWidget(self.columnView_4, 2, 8, 1, 1)
        self.columnView_20 = QtWidgets.QColumnView(self.verticalLayoutWidget)
        self.columnView_20.setMinimumSize(QtCore.QSize(80, 80))
        self.columnView_20.setMaximumSize(QtCore.QSize(80, 80))
        self.columnView_20.setObjectName("columnView_20")
        self.gridLayout_2.addWidget(self.columnView_20, 6, 8, 1, 1)
        self.columnView_17 = QtWidgets.QColumnView(self.verticalLayoutWidget)
        self.columnView_17.setMinimumSize(QtCore.QSize(80, 80))
        self.columnView_17.setMaximumSize(QtCore.QSize(80, 80))
        self.columnView_17.setObjectName("columnView_17")
        self.gridLayout_2.addWidget(self.columnView_17, 6, 6, 1, 1)
        self.labelA = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelA.setFont(font)
        self.labelA.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelA.setObjectName("labelA")
        self.gridLayout_2.addWidget(self.labelA, 12, 1, 1, 2)
        self.columnView_3 = QtWidgets.QColumnView(self.verticalLayoutWidget)
        self.columnView_3.setMinimumSize(QtCore.QSize(80, 80))
        self.columnView_3.setMaximumSize(QtCore.QSize(80, 80))
        self.columnView_3.setObjectName("columnView_3")
        self.gridLayout_2.addWidget(self.columnView_3, 2, 6, 1, 1)
        self.columnView_8 = QtWidgets.QColumnView(self.verticalLayoutWidget)
        self.columnView_8.setMinimumSize(QtCore.QSize(80, 80))
        self.columnView_8.setMaximumSize(QtCore.QSize(80, 80))
        self.columnView_8.setObjectName("columnView_8")
        self.gridLayout_2.addWidget(self.columnView_8, 8, 2, 1, 1)
        self.label4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label4.setFont(font)
        self.label4.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label4.setObjectName("label4")
        self.gridLayout_2.addWidget(self.label4, 4, 0, 2, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 12, 11, 1)
        self.columnView_11 = QtWidgets.QColumnView(self.verticalLayoutWidget)
        self.columnView_11.setMinimumSize(QtCore.QSize(80, 80))
        self.columnView_11.setMaximumSize(QtCore.QSize(80, 80))
        self.columnView_11.setObjectName("columnView_11")
        self.gridLayout_2.addWidget(self.columnView_11, 6, 4, 1, 1)
        self.columnView_22 = QtWidgets.QColumnView(self.verticalLayoutWidget)
        self.columnView_22.setMinimumSize(QtCore.QSize(80, 80))
        self.columnView_22.setMaximumSize(QtCore.QSize(80, 80))
        self.columnView_22.setObjectName("columnView_22")
        self.gridLayout_2.addWidget(self.columnView_22, 6, 10, 1, 1)
        self.columnView_13 = QtWidgets.QColumnView(self.verticalLayoutWidget)
        self.columnView_13.setMinimumSize(QtCore.QSize(80, 80))
        self.columnView_13.setMaximumSize(QtCore.QSize(80, 80))
        self.columnView_13.setObjectName("columnView_13")
        self.gridLayout_2.addWidget(self.columnView_13, 10, 4, 1, 1)
        self.columnView_12 = QtWidgets.QColumnView(self.verticalLayoutWidget)
        self.columnView_12.setMinimumSize(QtCore.QSize(80, 80))
        self.columnView_12.setMaximumSize(QtCore.QSize(80, 80))
        self.columnView_12.setObjectName("columnView_12")
        self.gridLayout_2.addWidget(self.columnView_12, 8, 4, 1, 1)
        self.columnView_21 = QtWidgets.QColumnView(self.verticalLayoutWidget)
        self.columnView_21.setMinimumSize(QtCore.QSize(80, 80))
        self.columnView_21.setMaximumSize(QtCore.QSize(80, 80))
        self.columnView_21.setObjectName("columnView_21")
        self.gridLayout_2.addWidget(self.columnView_21, 4, 10, 1, 1)
        self.columnView_7 = QtWidgets.QColumnView(self.verticalLayoutWidget)
        self.columnView_7.setMinimumSize(QtCore.QSize(80, 80))
        self.columnView_7.setMaximumSize(QtCore.QSize(80, 80))
        self.columnView_7.setObjectName("columnView_7")
        self.gridLayout_2.addWidget(self.columnView_7, 6, 2, 1, 1)
        self.columnView_10 = QtWidgets.QColumnView(self.verticalLayoutWidget)
        self.columnView_10.setMinimumSize(QtCore.QSize(80, 80))
        self.columnView_10.setMaximumSize(QtCore.QSize(80, 80))
        self.columnView_10.setObjectName("columnView_10")
        self.gridLayout_2.addWidget(self.columnView_10, 4, 4, 1, 1)
        self.label3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label3.setFont(font)
        self.label3.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label3.setObjectName("label3")
        self.gridLayout_2.addWidget(self.label3, 6, 0, 2, 1)
        self.labelC = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelC.setFont(font)
        self.labelC.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelC.setObjectName("labelC")
        self.gridLayout_2.addWidget(self.labelC, 12, 5, 1, 2)
        self.label5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label5.setFont(font)
        self.label5.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label5.setObjectName("label5")
        self.gridLayout_2.addWidget(self.label5, 2, 0, 2, 1)
        self.columnView_23 = QtWidgets.QColumnView(self.verticalLayoutWidget)
        self.columnView_23.setMinimumSize(QtCore.QSize(80, 80))
        self.columnView_23.setMaximumSize(QtCore.QSize(80, 80))
        self.columnView_23.setObjectName("columnView_23")
        self.gridLayout_2.addWidget(self.columnView_23, 8, 10, 1, 1)
        self.buttonD3h = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonD3h.setMinimumSize(QtCore.QSize(80, 10))
        self.buttonD3h.setMaximumSize(QtCore.QSize(80, 10))
        self.buttonD3h.setText("")
        self.buttonD3h.setIconSize(QtCore.QSize(50, 3))
        self.buttonD3h.setObjectName("buttond3h")
        self.gridLayout_2.addWidget(self.buttonD3h, 7, 8, 1, 1)
        self.buttonF5v = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonF5v.setMinimumSize(QtCore.QSize(10, 80))
        self.buttonF5v.setMaximumSize(QtCore.QSize(10, 80))
        self.buttonF5v.setText("")
        self.buttonF5v.setObjectName("buttonf5v")
        self.gridLayout_2.addWidget(self.buttonF5v, 2, 11, 1, 1)
        self.buttonC5h = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonC5h.setMinimumSize(QtCore.QSize(80, 10))
        self.buttonC5h.setMaximumSize(QtCore.QSize(80, 10))
        self.buttonC5h.setText("")
        self.buttonC5h.setIconSize(QtCore.QSize(50, 3))
        self.buttonC5h.setObjectName("buttonc5h")
        self.gridLayout_2.addWidget(self.buttonC5h, 3, 6, 1, 1)
        self.buttonE5v = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonE5v.setMinimumSize(QtCore.QSize(10, 80))
        self.buttonE5v.setMaximumSize(QtCore.QSize(10, 80))
        self.buttonE5v.setText("")
        self.buttonE5v.setObjectName("buttone5v")
        self.gridLayout_2.addWidget(self.buttonE5v, 2, 9, 1, 1)
        self.buttonD4h = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonD4h.setMinimumSize(QtCore.QSize(80, 10))
        self.buttonD4h.setMaximumSize(QtCore.QSize(80, 10))
        self.buttonD4h.setText("")
        self.buttonD4h.setIconSize(QtCore.QSize(50, 3))
        self.buttonD4h.setObjectName("buttond4h")
        self.gridLayout_2.addWidget(self.buttonD4h, 5, 8, 1, 1)
        self.buttonD3v = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonD3v.setMinimumSize(QtCore.QSize(10, 80))
        self.buttonD3v.setMaximumSize(QtCore.QSize(10, 80))
        self.buttonD3v.setText("")
        self.buttonD3v.setObjectName("buttond3v")
        self.gridLayout_2.addWidget(self.buttonD3v, 6, 7, 1, 1)
        self.buttonD5v = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonD5v.setMinimumSize(QtCore.QSize(10, 80))
        self.buttonD5v.setMaximumSize(QtCore.QSize(10, 80))
        self.buttonD5v.setText("")
        self.buttonD5v.setObjectName("buttond5v")
        self.gridLayout_2.addWidget(self.buttonD5v, 2, 7, 1, 1)
        self.buttonB4v = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonB4v.setMinimumSize(QtCore.QSize(10, 80))
        self.buttonB4v.setMaximumSize(QtCore.QSize(10, 80))
        self.buttonB4v.setText("")
        self.buttonB4v.setObjectName("buttonb4v")
        self.gridLayout_2.addWidget(self.buttonB4v, 4, 3, 1, 1)
        self.buttonD1h = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonD1h.setMinimumSize(QtCore.QSize(80, 10))
        self.buttonD1h.setMaximumSize(QtCore.QSize(80, 10))
        self.buttonD1h.setText("")
        self.buttonD1h.setIconSize(QtCore.QSize(50, 3))
        self.buttonD1h.setObjectName("buttond1h")
        self.gridLayout_2.addWidget(self.buttonD1h, 11, 8, 1, 1)
        self.buttonD4v = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonD4v.setMinimumSize(QtCore.QSize(10, 80))
        self.buttonD4v.setMaximumSize(QtCore.QSize(10, 80))
        self.buttonD4v.setText("")
        self.buttonD4v.setObjectName("buttond4v")
        self.gridLayout_2.addWidget(self.buttonD4v, 4, 7, 1, 1)
        self.buttonB2v = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonB2v.setMinimumSize(QtCore.QSize(10, 80))
        self.buttonB2v.setMaximumSize(QtCore.QSize(10, 80))
        self.buttonB2v.setText("")
        self.buttonB2v.setObjectName("buttonb2v")
        self.gridLayout_2.addWidget(self.buttonB2v, 8, 3, 1, 1)
        self.buttonE2h = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonE2h.setMinimumSize(QtCore.QSize(80, 10))
        self.buttonE2h.setMaximumSize(QtCore.QSize(80, 10))
        self.buttonE2h.setText("")
        self.buttonE2h.setIconSize(QtCore.QSize(50, 3))
        self.buttonE2h.setObjectName("buttone2h")
        self.gridLayout_2.addWidget(self.buttonE2h, 9, 10, 1, 1)
        self.buttonE6h = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonE6h.setMinimumSize(QtCore.QSize(80, 10))
        self.buttonE6h.setMaximumSize(QtCore.QSize(80, 10))
        self.buttonE6h.setText("")
        self.buttonE6h.setIconSize(QtCore.QSize(50, 3))
        self.buttonE6h.setObjectName("buttone6h")
        self.gridLayout_2.addWidget(self.buttonE6h, 1, 10, 1, 1)
        self.buttonC1h = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonC1h.setMinimumSize(QtCore.QSize(80, 10))
        self.buttonC1h.setMaximumSize(QtCore.QSize(80, 10))
        self.buttonC1h.setText("")
        self.buttonC1h.setIconSize(QtCore.QSize(50, 3))
        self.buttonC1h.setObjectName("buttonc1h")
        self.gridLayout_2.addWidget(self.buttonC1h, 11, 6, 1, 1)
        self.buttonB2h = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonB2h.setMinimumSize(QtCore.QSize(80, 10))
        self.buttonB2h.setMaximumSize(QtCore.QSize(80, 10))
        self.buttonB2h.setText("")
        self.buttonB2h.setIconSize(QtCore.QSize(50, 3))
        self.buttonB2h.setObjectName("buttonb2h")
        self.gridLayout_2.addWidget(self.buttonB2h, 9, 4, 1, 1)
        self.buttonA1v = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonA1v.setMinimumSize(QtCore.QSize(10, 80))
        self.buttonA1v.setMaximumSize(QtCore.QSize(10, 80))
        self.buttonA1v.setText("")
        self.buttonA1v.setObjectName("buttona1v")
        self.gridLayout_2.addWidget(self.buttonA1v, 10, 1, 1, 1)
        self.buttonA4v = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonA4v.setMinimumSize(QtCore.QSize(10, 80))
        self.buttonA4v.setMaximumSize(QtCore.QSize(10, 80))
        self.buttonA4v.setText("")
        self.buttonA4v.setObjectName("buttona4v")
        self.gridLayout_2.addWidget(self.buttonA4v, 4, 1, 1, 1)
        self.buttonB1h = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonB1h.setMinimumSize(QtCore.QSize(80, 10))
        self.buttonB1h.setMaximumSize(QtCore.QSize(80, 10))
        self.buttonB1h.setText("")
        self.buttonB1h.setIconSize(QtCore.QSize(50, 3))
        self.buttonB1h.setObjectName("buttonb1h")
        self.gridLayout_2.addWidget(self.buttonB1h, 11, 4, 1, 1)
        self.buttonC5v = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonC5v.setMinimumSize(QtCore.QSize(10, 80))
        self.buttonC5v.setMaximumSize(QtCore.QSize(10, 80))
        self.buttonC5v.setText("")
        self.buttonC5v.setObjectName("buttonc5v")
        self.gridLayout_2.addWidget(self.buttonC5v, 2, 5, 1, 1)
        self.buttonF2v = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonF2v.setMinimumSize(QtCore.QSize(10, 80))
        self.buttonF2v.setMaximumSize(QtCore.QSize(10, 80))
        self.buttonF2v.setText("")
        self.buttonF2v.setObjectName("buttonf2v")
        self.gridLayout_2.addWidget(self.buttonF2v, 8, 11, 1, 1)
        self.buttonD5h = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonD5h.setMinimumSize(QtCore.QSize(80, 10))
        self.buttonD5h.setMaximumSize(QtCore.QSize(80, 10))
        self.buttonD5h.setText("")
        self.buttonD5h.setIconSize(QtCore.QSize(50, 3))
        self.buttonD5h.setObjectName("buttond5h")
        self.gridLayout_2.addWidget(self.buttonD5h, 3, 8, 1, 1)
        self.buttonD2v = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonD2v.setMinimumSize(QtCore.QSize(10, 80))
        self.buttonD2v.setMaximumSize(QtCore.QSize(10, 80))
        self.buttonD2v.setText("")
        self.buttonD2v.setObjectName("buttond2v")
        self.gridLayout_2.addWidget(self.buttonD2v, 8, 7, 1, 1)
        self.buttonC2h = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonC2h.setMinimumSize(QtCore.QSize(80, 10))
        self.buttonC2h.setMaximumSize(QtCore.QSize(80, 10))
        self.buttonC2h.setText("")
        self.buttonC2h.setIconSize(QtCore.QSize(50, 3))
        self.buttonC2h.setObjectName("buttonc2h")
        self.gridLayout_2.addWidget(self.buttonC2h, 9, 6, 1, 1)
        self.buttonC3h = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonC3h.setMinimumSize(QtCore.QSize(80, 10))
        self.buttonC3h.setMaximumSize(QtCore.QSize(80, 10))
        self.buttonC3h.setText("")
        self.buttonC3h.setIconSize(QtCore.QSize(50, 3))
        self.buttonC3h.setObjectName("buttonc3h")
        self.gridLayout_2.addWidget(self.buttonC3h, 7, 6, 1, 1)
        self.buttonD1v = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonD1v.setMinimumSize(QtCore.QSize(10, 80))
        self.buttonD1v.setMaximumSize(QtCore.QSize(10, 80))
        self.buttonD1v.setText("")
        self.buttonD1v.setObjectName("buttond1v")
        self.gridLayout_2.addWidget(self.buttonD1v, 10, 7, 1, 1)
        self.buttonE5h = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonE5h.setMinimumSize(QtCore.QSize(80, 10))
        self.buttonE5h.setMaximumSize(QtCore.QSize(80, 10))
        self.buttonE5h.setText("")
        self.buttonE5h.setIconSize(QtCore.QSize(50, 3))
        self.buttonE5h.setObjectName("buttone5h")
        self.gridLayout_2.addWidget(self.buttonE5h, 3, 10, 1, 1)
        self.buttonF1v = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonF1v.setMinimumSize(QtCore.QSize(10, 80))
        self.buttonF1v.setMaximumSize(QtCore.QSize(10, 80))
        self.buttonF1v.setText("")
        self.buttonF1v.setObjectName("buttonf1v")
        self.gridLayout_2.addWidget(self.buttonF1v, 10, 11, 1, 1)
        self.buttonB3h = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonB3h.setMinimumSize(QtCore.QSize(80, 10))
        self.buttonB3h.setMaximumSize(QtCore.QSize(80, 10))
        self.buttonB3h.setText("")
        self.buttonB3h.setIconSize(QtCore.QSize(50, 3))
        self.buttonB3h.setObjectName("buttonb3h")
        self.gridLayout_2.addWidget(self.buttonB3h, 7, 4, 1, 1)
        self.buttonC4v = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonC4v.setMinimumSize(QtCore.QSize(10, 80))
        self.buttonC4v.setMaximumSize(QtCore.QSize(10, 80))
        self.buttonC4v.setText("")
        self.buttonC4v.setObjectName("buttonc4v")
        self.gridLayout_2.addWidget(self.buttonC4v, 4, 5, 1, 1)
        self.buttonD6h = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonD6h.setMinimumSize(QtCore.QSize(80, 10))
        self.buttonD6h.setMaximumSize(QtCore.QSize(80, 10))
        self.buttonD6h.setText("")
        self.buttonD6h.setIconSize(QtCore.QSize(50, 3))
        self.buttonD6h.setObjectName("buttond6h")
        self.gridLayout_2.addWidget(self.buttonD6h, 1, 8, 1, 1)
        self.buttonE2v = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonE2v.setMinimumSize(QtCore.QSize(10, 80))
        self.buttonE2v.setMaximumSize(QtCore.QSize(10, 80))
        self.buttonE2v.setText("")
        self.buttonE2v.setObjectName("buttone2v")
        self.gridLayout_2.addWidget(self.buttonE2v, 8, 9, 1, 1)
        self.buttonA4h = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonA4h.setMinimumSize(QtCore.QSize(80, 10))
        self.buttonA4h.setMaximumSize(QtCore.QSize(80, 10))
        self.buttonA4h.setText("")
        self.buttonA4h.setIconSize(QtCore.QSize(50, 3))
        self.buttonA4h.setObjectName("buttona4h")
        self.gridLayout_2.addWidget(self.buttonA4h, 5, 2, 1, 1)
        self.buttonE4v = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonE4v.setMinimumSize(QtCore.QSize(10, 80))
        self.buttonE4v.setMaximumSize(QtCore.QSize(10, 80))
        self.buttonE4v.setText("")
        self.buttonE4v.setObjectName("buttone4v")
        self.gridLayout_2.addWidget(self.buttonE4v, 4, 9, 1, 1)
        self.buttonA2h = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonA2h.setMinimumSize(QtCore.QSize(80, 10))
        self.buttonA2h.setMaximumSize(QtCore.QSize(80, 10))
        self.buttonA2h.setText("")
        self.buttonA2h.setIconSize(QtCore.QSize(50, 3))
        self.buttonA2h.setObjectName("buttona2h")
        self.gridLayout_2.addWidget(self.buttonA2h, 9, 2, 1, 1)
        self.buttonC3v = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonC3v.setMinimumSize(QtCore.QSize(10, 80))
        self.buttonC3v.setMaximumSize(QtCore.QSize(10, 80))
        self.buttonC3v.setText("")
        self.buttonC3v.setObjectName("buttonc3v")
        self.gridLayout_2.addWidget(self.buttonC3v, 6, 5, 1, 1)
        self.buttonA3v = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonA3v.setMinimumSize(QtCore.QSize(10, 80))
        self.buttonA3v.setMaximumSize(QtCore.QSize(10, 80))
        self.buttonA3v.setText("")
        self.buttonA3v.setObjectName("buttona3v")
        self.gridLayout_2.addWidget(self.buttonA3v, 6, 1, 1, 1)
        self.buttonA6h = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonA6h.setMinimumSize(QtCore.QSize(80, 10))
        self.buttonA6h.setMaximumSize(QtCore.QSize(80, 10))
        self.buttonA6h.setText("")
        self.buttonA6h.setIconSize(QtCore.QSize(50, 3))
        self.buttonA6h.setObjectName("buttona6h")
        self.gridLayout_2.addWidget(self.buttonA6h, 1, 2, 1, 1)
        self.buttonC2v = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonC2v.setMinimumSize(QtCore.QSize(10, 80))
        self.buttonC2v.setMaximumSize(QtCore.QSize(10, 80))
        self.buttonC2v.setText("")
        self.buttonC2v.setObjectName("buttonc2v")
        self.gridLayout_2.addWidget(self.buttonC2v, 8, 5, 1, 1)
        self.buttonE1v = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonE1v.setMinimumSize(QtCore.QSize(10, 80))
        self.buttonE1v.setMaximumSize(QtCore.QSize(10, 80))
        self.buttonE1v.setText("")
        self.buttonE1v.setObjectName("buttone1v")
        self.gridLayout_2.addWidget(self.buttonE1v, 10, 9, 1, 1)
        self.buttonF3v = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonF3v.setMinimumSize(QtCore.QSize(10, 80))
        self.buttonF3v.setMaximumSize(QtCore.QSize(10, 80))
        self.buttonF3v.setText("")
        self.buttonF3v.setObjectName("buttonf3v")
        self.gridLayout_2.addWidget(self.buttonF3v, 6, 11, 1, 1)
        self.buttonF4v = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonF4v.setMinimumSize(QtCore.QSize(10, 80))
        self.buttonF4v.setMaximumSize(QtCore.QSize(10, 80))
        self.buttonF4v.setText("")
        self.buttonF4v.setObjectName("buttonf4v")
        self.gridLayout_2.addWidget(self.buttonF4v, 4, 11, 1, 1)
        self.buttonC6h = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonC6h.setMinimumSize(QtCore.QSize(80, 10))
        self.buttonC6h.setMaximumSize(QtCore.QSize(80, 10))
        self.buttonC6h.setText("")
        self.buttonC6h.setIconSize(QtCore.QSize(50, 3))
        self.buttonC6h.setObjectName("buttonc6h")
        self.gridLayout_2.addWidget(self.buttonC6h, 1, 6, 1, 1)
        self.buttonE3h = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonE3h.setMinimumSize(QtCore.QSize(80, 10))
        self.buttonE3h.setMaximumSize(QtCore.QSize(80, 10))
        self.buttonE3h.setText("")
        self.buttonE3h.setIconSize(QtCore.QSize(50, 3))
        self.buttonE3h.setObjectName("buttone3h")
        self.gridLayout_2.addWidget(self.buttonE3h, 7, 10, 1, 1)
        self.buttonE1h = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonE1h.setMinimumSize(QtCore.QSize(80, 10))
        self.buttonE1h.setMaximumSize(QtCore.QSize(80, 10))
        self.buttonE1h.setText("")
        self.buttonE1h.setIconSize(QtCore.QSize(50, 3))
        self.buttonE1h.setObjectName("buttone1h")
        self.gridLayout_2.addWidget(self.buttonE1h, 11, 10, 1, 1)
        self.buttonA5v = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonA5v.setMinimumSize(QtCore.QSize(10, 80))
        self.buttonA5v.setMaximumSize(QtCore.QSize(10, 80))
        self.buttonA5v.setText("")
        self.buttonA5v.setObjectName("buttona5v")
        self.gridLayout_2.addWidget(self.buttonA5v, 2, 1, 1, 1)
        self.buttonD2h = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonD2h.setMinimumSize(QtCore.QSize(80, 10))
        self.buttonD2h.setMaximumSize(QtCore.QSize(80, 10))
        self.buttonD2h.setText("")
        self.buttonD2h.setIconSize(QtCore.QSize(50, 3))
        self.buttonD2h.setObjectName("buttond2h")
        self.gridLayout_2.addWidget(self.buttonD2h, 9, 8, 1, 1)
        self.buttonA2v = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonA2v.setMinimumSize(QtCore.QSize(10, 80))
        self.buttonA2v.setMaximumSize(QtCore.QSize(10, 80))
        self.buttonA2v.setText("")
        self.buttonA2v.setObjectName("buttona2v")
        self.gridLayout_2.addWidget(self.buttonA2v, 8, 1, 1, 1)
        self.buttonA5h = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonA5h.setMinimumSize(QtCore.QSize(80, 10))
        self.buttonA5h.setMaximumSize(QtCore.QSize(80, 10))
        self.buttonA5h.setText("")
        self.buttonA5h.setIconSize(QtCore.QSize(50, 3))
        self.buttonA5h.setObjectName("buttona5h")
        self.gridLayout_2.addWidget(self.buttonA5h, 3, 2, 1, 1)
        self.buttonB5v = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonB5v.setMinimumSize(QtCore.QSize(10, 80))
        self.buttonB5v.setMaximumSize(QtCore.QSize(10, 80))
        self.buttonB5v.setText("")
        self.buttonB5v.setObjectName("buttonb5v")
        self.gridLayout_2.addWidget(self.buttonB5v, 2, 3, 1, 1)
        self.buttonE3v = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonE3v.setMinimumSize(QtCore.QSize(10, 80))
        self.buttonE3v.setMaximumSize(QtCore.QSize(10, 80))
        self.buttonE3v.setText("")
        self.buttonE3v.setObjectName("buttone3v")
        self.gridLayout_2.addWidget(self.buttonE3v, 6, 9, 1, 1)
        self.buttonA3h = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonA3h.setMinimumSize(QtCore.QSize(80, 10))
        self.buttonA3h.setMaximumSize(QtCore.QSize(80, 10))
        self.buttonA3h.setText("")
        self.buttonA3h.setIconSize(QtCore.QSize(50, 3))
        self.buttonA3h.setObjectName("buttona3h")
        self.gridLayout_2.addWidget(self.buttonA3h, 7, 2, 1, 1)
        self.buttonC1v = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonC1v.setMinimumSize(QtCore.QSize(10, 80))
        self.buttonC1v.setMaximumSize(QtCore.QSize(10, 80))
        self.buttonC1v.setText("")
        self.buttonC1v.setObjectName("buttonc1v")
        self.gridLayout_2.addWidget(self.buttonC1v, 10, 5, 1, 1)
        self.buttonA1h = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonA1h.setMinimumSize(QtCore.QSize(80, 10))
        self.buttonA1h.setMaximumSize(QtCore.QSize(80, 10))
        self.buttonA1h.setText("")
        self.buttonA1h.setIconSize(QtCore.QSize(50, 3))
        self.buttonA1h.setObjectName("buttona1h")
        self.gridLayout_2.addWidget(self.buttonA1h, 11, 2, 1, 1)
        self.buttonE4h = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonE4h.setMinimumSize(QtCore.QSize(80, 10))
        self.buttonE4h.setMaximumSize(QtCore.QSize(80, 10))
        self.buttonE4h.setText("")
        self.buttonE4h.setIconSize(QtCore.QSize(50, 3))
        self.buttonE4h.setObjectName("buttone4h")
        self.gridLayout_2.addWidget(self.buttonE4h, 5, 10, 1, 1)
        self.buttonB1v = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonB1v.setMinimumSize(QtCore.QSize(10, 80))
        self.buttonB1v.setMaximumSize(QtCore.QSize(10, 80))
        self.buttonB1v.setText("")
        self.buttonB1v.setObjectName("buttonb1v")
        self.gridLayout_2.addWidget(self.buttonB1v, 10, 3, 1, 1)
        self.buttonB6h = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonB6h.setMinimumSize(QtCore.QSize(80, 10))
        self.buttonB6h.setMaximumSize(QtCore.QSize(80, 10))
        self.buttonB6h.setText("")
        self.buttonB6h.setIconSize(QtCore.QSize(50, 3))
        self.buttonB6h.setObjectName("buttonb6h")
        self.gridLayout_2.addWidget(self.buttonB6h, 1, 4, 1, 1)
        self.buttonC4h = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonC4h.setMinimumSize(QtCore.QSize(80, 10))
        self.buttonC4h.setMaximumSize(QtCore.QSize(80, 10))
        self.buttonC4h.setText("")
        self.buttonC4h.setObjectName("buttonc4h")
        self.gridLayout_2.addWidget(self.buttonC4h, 5, 6, 1, 1)
        self.buttonB3v = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonB3v.setMinimumSize(QtCore.QSize(10, 80))
        self.buttonB3v.setMaximumSize(QtCore.QSize(10, 80))
        self.buttonB3v.setText("")
        self.buttonB3v.setObjectName("buttonb3v")
        self.gridLayout_2.addWidget(self.buttonB3v, 6, 3, 1, 1)
        self.buttonB4h = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonB4h.setMinimumSize(QtCore.QSize(80, 10))
        self.buttonB4h.setMaximumSize(QtCore.QSize(80, 10))
        self.buttonB4h.setText("")
        self.buttonB4h.setIconSize(QtCore.QSize(50, 3))
        self.buttonB4h.setObjectName("buttonb4h")
        self.gridLayout_2.addWidget(self.buttonB4h, 5, 4, 1, 1)
        self.buttonB5h = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonB5h.setMinimumSize(QtCore.QSize(80, 10))
        self.buttonB5h.setMaximumSize(QtCore.QSize(80, 10))
        self.buttonB5h.setText("")
        self.buttonB5h.setIconSize(QtCore.QSize(50, 3))
        self.buttonB5h.setObjectName("buttonb5h")
        self.gridLayout_2.addWidget(self.buttonB5h, 3, 4, 1, 1)
        self.labelB = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelB.setFont(font)
        self.labelB.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelB.setObjectName("labelB")
        self.gridLayout_2.addWidget(self.labelB, 12, 3, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 0, 1, 1, 11)
        self.labelF = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelF.setFont(font)
        self.labelF.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelF.setObjectName("labelF")
        self.gridLayout_2.addWidget(self.labelF, 12, 11, 1, 2)
        self.label2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label2.setFont(font)
        self.label2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label2.setObjectName("label2")
        self.gridLayout_2.addWidget(self.label2, 8, 0, 2, 1)
        self.labelE = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelE.setFont(font)
        self.labelE.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelE.setObjectName("labelE")
        self.gridLayout_2.addWidget(self.labelE, 12, 9, 1, 2)
        self.horizontalLayout.addLayout(self.gridLayout_2)
        self.line_3 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout.addWidget(self.line_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_13.setMinimumSize(QtCore.QSize(25, 30))
        self.label_13.setMaximumSize(QtCore.QSize(25, 30))
        font = QtGui.QFont()
        font.setPointSize(38)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setIndent(20)
        self.label_13.setMargin(-20)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 3, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_14.setMinimumSize(QtCore.QSize(25, 30))
        self.label_14.setMaximumSize(QtCore.QSize(25, 30))
        font = QtGui.QFont()
        font.setPointSize(38)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setIndent(20)
        self.label_14.setMargin(-20)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 3, 3, 1, 1)
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.verticalLayoutWidget)
        self.lcdNumber_2.setMinimumSize(QtCore.QSize(40, 25))
        self.lcdNumber_2.setMaximumSize(QtCore.QSize(40, 25))
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.gridLayout_3.addWidget(self.lcdNumber_2, 3, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_15.setMinimumSize(QtCore.QSize(0, 35))
        self.label_15.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 2, 1, 1, 4)
        self.lcdNumber = QtWidgets.QLCDNumber(self.verticalLayoutWidget)
        self.lcdNumber.setMinimumSize(QtCore.QSize(40, 25))
        self.lcdNumber.setMaximumSize(QtCore.QSize(40, 25))
        self.lcdNumber.setObjectName("lcdNumber")
        self.gridLayout_3.addWidget(self.lcdNumber, 3, 4, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 2, 5, 2, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 2, 0, 2, 1)
        self.currentStepTextLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.currentStepTextLabel.setMinimumSize(QtCore.QSize(0, 35))
        self.currentStepTextLabel.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.currentStepTextLabel.setFont(font)
        self.currentStepTextLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.currentStepTextLabel.setObjectName("currentStepTextLabel")
        self.gridLayout_3.addWidget(self.currentStepTextLabel, 1, 0, 1, 3)
        self.currentPlayerTextLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.currentPlayerTextLabel.setMinimumSize(QtCore.QSize(0, 35))
        self.currentPlayerTextLabel.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.currentPlayerTextLabel.setFont(font)
        self.currentPlayerTextLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.currentPlayerTextLabel.setObjectName("currentPlayerTextLabel")
        self.gridLayout_3.addWidget(self.currentPlayerTextLabel, 0, 0, 1, 3)
        self.currentStepLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.currentStepLabel.setMinimumSize(QtCore.QSize(0, 35))
        self.currentStepLabel.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.currentStepLabel.setFont(font)
        self.currentStepLabel.setObjectName("currentStepLabel")
        self.gridLayout_3.addWidget(self.currentStepLabel, 1, 3, 1, 3)
        self.currentPlayerLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.currentPlayerLabel.setMinimumSize(QtCore.QSize(0, 35))
        self.currentPlayerLabel.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setPointSize(45)
        font.setKerning(False)
        self.currentPlayerLabel.setFont(font)
        self.currentPlayerLabel.setAutoFillBackground(False)
        self.currentPlayerLabel.setIndent(35)
        self.currentPlayerLabel.setMargin(-30)
        self.currentPlayerLabel.setObjectName("currentPlayerLabel")
        self.gridLayout_3.addWidget(self.currentPlayerLabel, 0, 3, 1, 3)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.line_4 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_2.addWidget(self.line_4)
        self.label_16 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_2.addWidget(self.label_16)
        self.history_tableView = QtWidgets.QTableView(self.verticalLayoutWidget)
        self.history_tableView.setObjectName("history_tableView")
        self.history_tableView.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Custom)
        self.verticalLayout_2.addWidget(self.history_tableView)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line_2 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 731, 31))
        self.menubar.setObjectName("menubar")
        self.menu0 = QtWidgets.QMenu(self.menubar)
        self.menu0.setObjectName("menu0")
        self.menu1 = QtWidgets.QMenu(self.menubar)
        self.menu1.setObjectName("menu1")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action00 = QtWidgets.QAction(MainWindow)
        self.action00.setObjectName("action00")
        self.action01 = QtWidgets.QAction(MainWindow)
        self.action01.setObjectName("action01")
        self.action02 = QtWidgets.QAction(MainWindow)
        self.action02.setObjectName("action02")
        self.action03 = QtWidgets.QAction(MainWindow)
        self.action03.setObjectName("action03")
        self.action10 = QtWidgets.QAction(MainWindow)
        self.action10.setObjectName("action10")
        self.action11 = QtWidgets.QAction(MainWindow)
        self.action11.setObjectName("action11")
        self.menu0.addAction(self.action00)
        self.menu0.addAction(self.action01)
        self.menu0.addSeparator()
        self.menu0.addAction(self.action02)
        self.menu0.addAction(self.action03)
        self.menu1.addAction(self.action10)
        self.menu1.addAction(self.action11)
        self.menubar.addAction(self.menu0.menuAction())
        self.menubar.addAction(self.menu1.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "点格棋"))
        self.label6.setText(_translate("MainWindow", "6"))
        self.label1.setText(_translate("MainWindow", "1"))
        self.labelD.setText(_translate("MainWindow", "D"))
        self.labelA.setText(_translate("MainWindow", "A"))
        self.label4.setText(_translate("MainWindow", "4"))
        self.label3.setText(_translate("MainWindow", "3"))
        self.labelC.setText(_translate("MainWindow", "C"))
        self.label5.setText(_translate("MainWindow", "5"))
        self.labelB.setText(_translate("MainWindow", "B"))
        self.labelF.setText(_translate("MainWindow", "F"))
        self.label2.setText(_translate("MainWindow", "2"))
        self.labelE.setText(_translate("MainWindow", "E"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ff0000;\">•</span></p></body></html>"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#0055ff;\">•</span></p></body></html>"))
        self.label_15.setText(_translate("MainWindow", "比  分"))
        self.currentStepTextLabel.setText(_translate("MainWindow", "当前步数: "))
        self.currentPlayerTextLabel.setText(_translate("MainWindow", "当前玩家: "))
        self.currentStepLabel.setText(_translate("MainWindow", "0"))
        self.label_16.setText(_translate("MainWindow", "历史: "))
        self.menu0.setTitle(_translate("MainWindow", "文件"))
        self.menu1.setTitle(_translate("MainWindow", "编辑"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.action00.setText(_translate("MainWindow", "新游戏"))
        self.action01.setText(_translate("MainWindow", "载入游戏"))
        self.action02.setText(_translate("MainWindow", "保存游戏"))
        self.action03.setText(_translate("MainWindow", "导出标准棋谱"))
        self.action10.setText(_translate("MainWindow", "悔棋"))
        self.action11.setText(_translate("MainWindow", "恢复"))


class MainWindow(QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self, controller, parent=None):
        super(MainWindow, self).__init__(parent)
        self.setupUi(self)

        self._controller = controller

        self.buttonA1h.clicked.connect(lambda: self._controller.piece_button_is_clicked(('a', '1', 'h'), self.buttonA1h))
        self.buttonA1v.clicked.connect(lambda: self._controller.piece_button_is_clicked(('a', '1', 'v'), self.buttonA1v))
        self.buttonA2h.clicked.connect(lambda: self._controller.piece_button_is_clicked(('a', '2', 'h'), self.buttonA2h))
        self.buttonA2v.clicked.connect(lambda: self._controller.piece_button_is_clicked(('a', '2', 'v'), self.buttonA2v))
        self.buttonA3h.clicked.connect(lambda: self._controller.piece_button_is_clicked(('a', '3', 'h'), self.buttonA3h))
        self.buttonA3v.clicked.connect(lambda: self._controller.piece_button_is_clicked(('a', '3', 'v'), self.buttonA3v))
        self.buttonA4h.clicked.connect(lambda: self._controller.piece_button_is_clicked(('a', '4', 'h'), self.buttonA4h))
        self.buttonA4v.clicked.connect(lambda: self._controller.piece_button_is_clicked(('a', '4', 'v'), self.buttonA4v))
        self.buttonA5h.clicked.connect(lambda: self._controller.piece_button_is_clicked(('a', '5', 'h'), self.buttonA5h))
        self.buttonA5v.clicked.connect(lambda: self._controller.piece_button_is_clicked(('a', '5', 'v'), self.buttonA5v))
        self.buttonA6h.clicked.connect(lambda: self._controller.piece_button_is_clicked(('a', '6', 'h'), self.buttonA6h))
        self.buttonB1h.clicked.connect(lambda: self._controller.piece_button_is_clicked(('b', '1', 'h'), self.buttonB1h))
        self.buttonB1v.clicked.connect(lambda: self._controller.piece_button_is_clicked(('b', '1', 'v'), self.buttonB1v))
        self.buttonB2h.clicked.connect(lambda: self._controller.piece_button_is_clicked(('b', '2', 'h'), self.buttonB2h))
        self.buttonB2v.clicked.connect(lambda: self._controller.piece_button_is_clicked(('b', '2', 'v'), self.buttonB2v))
        self.buttonB3h.clicked.connect(lambda: self._controller.piece_button_is_clicked(('b', '3', 'h'), self.buttonB3h))
        self.buttonB3v.clicked.connect(lambda: self._controller.piece_button_is_clicked(('b', '3', 'v'), self.buttonB3v))
        self.buttonB4h.clicked.connect(lambda: self._controller.piece_button_is_clicked(('b', '4', 'h'), self.buttonB4h))
        self.buttonB4v.clicked.connect(lambda: self._controller.piece_button_is_clicked(('b', '4', 'v'), self.buttonB4v))
        self.buttonB5h.clicked.connect(lambda: self._controller.piece_button_is_clicked(('b', '5', 'h'), self.buttonB5h))
        self.buttonB5v.clicked.connect(lambda: self._controller.piece_button_is_clicked(('b', '5', 'v'), self.buttonB5v))
        self.buttonB6h.clicked.connect(lambda: self._controller.piece_button_is_clicked(('b', '6', 'h'), self.buttonB6h))
        self.buttonC1h.clicked.connect(lambda: self._controller.piece_button_is_clicked(('c', '1', 'h'), self.buttonC1h))
        self.buttonC1v.clicked.connect(lambda: self._controller.piece_button_is_clicked(('c', '1', 'v'), self.buttonC1v))
        self.buttonC2h.clicked.connect(lambda: self._controller.piece_button_is_clicked(('c', '2', 'h'), self.buttonC2h))
        self.buttonC2v.clicked.connect(lambda: self._controller.piece_button_is_clicked(('c', '2', 'v'), self.buttonC2v))
        self.buttonC3h.clicked.connect(lambda: self._controller.piece_button_is_clicked(('c', '3', 'h'), self.buttonC3h))
        self.buttonC3v.clicked.connect(lambda: self._controller.piece_button_is_clicked(('c', '3', 'v'), self.buttonC3v))
        self.buttonC4h.clicked.connect(lambda: self._controller.piece_button_is_clicked(('c', '4', 'h'), self.buttonC4h))
        self.buttonC4v.clicked.connect(lambda: self._controller.piece_button_is_clicked(('c', '4', 'v'), self.buttonC4v))
        self.buttonC5h.clicked.connect(lambda: self._controller.piece_button_is_clicked(('c', '5', 'h'), self.buttonC5h))
        self.buttonC5v.clicked.connect(lambda: self._controller.piece_button_is_clicked(('c', '5', 'v'), self.buttonC5v))
        self.buttonC6h.clicked.connect(lambda: self._controller.piece_button_is_clicked(('c', '6', 'h'), self.buttonC6h))
        self.buttonD1h.clicked.connect(lambda: self._controller.piece_button_is_clicked(('d', '1', 'h'), self.buttonD1h))
        self.buttonD1v.clicked.connect(lambda: self._controller.piece_button_is_clicked(('d', '1', 'v'), self.buttonD1v))
        self.buttonD2h.clicked.connect(lambda: self._controller.piece_button_is_clicked(('d', '2', 'h'), self.buttonD2h))
        self.buttonD2v.clicked.connect(lambda: self._controller.piece_button_is_clicked(('d', '2', 'v'), self.buttonD2v))
        self.buttonD3h.clicked.connect(lambda: self._controller.piece_button_is_clicked(('d', '3', 'h'), self.buttonD3h))
        self.buttonD3v.clicked.connect(lambda: self._controller.piece_button_is_clicked(('d', '3', 'v'), self.buttonD3v))
        self.buttonD4h.clicked.connect(lambda: self._controller.piece_button_is_clicked(('d', '4', 'h'), self.buttonD4h))
        self.buttonD4v.clicked.connect(lambda: self._controller.piece_button_is_clicked(('d', '4', 'v'), self.buttonD4v))
        self.buttonD5h.clicked.connect(lambda: self._controller.piece_button_is_clicked(('d', '5', 'h'), self.buttonD5h))
        self.buttonD5v.clicked.connect(lambda: self._controller.piece_button_is_clicked(('d', '5', 'v'), self.buttonD5v))
        self.buttonD6h.clicked.connect(lambda: self._controller.piece_button_is_clicked(('d', '6', 'h'), self.buttonD6h))
        self.buttonE1h.clicked.connect(lambda: self._controller.piece_button_is_clicked(('e', '1', 'h'), self.buttonE1h))
        self.buttonE1v.clicked.connect(lambda: self._controller.piece_button_is_clicked(('e', '1', 'v'), self.buttonE1v))
        self.buttonE2h.clicked.connect(lambda: self._controller.piece_button_is_clicked(('e', '2', 'h'), self.buttonE2h))
        self.buttonE2v.clicked.connect(lambda: self._controller.piece_button_is_clicked(('e', '2', 'v'), self.buttonE2v))
        self.buttonE3h.clicked.connect(lambda: self._controller.piece_button_is_clicked(('e', '3', 'h'), self.buttonE3h))
        self.buttonE3v.clicked.connect(lambda: self._controller.piece_button_is_clicked(('e', '3', 'v'), self.buttonE3v))
        self.buttonE4h.clicked.connect(lambda: self._controller.piece_button_is_clicked(('e', '4', 'h'), self.buttonE4h))
        self.buttonE4v.clicked.connect(lambda: self._controller.piece_button_is_clicked(('e', '4', 'v'), self.buttonE4v))
        self.buttonE5h.clicked.connect(lambda: self._controller.piece_button_is_clicked(('e', '5', 'h'), self.buttonE5h))
        self.buttonE5v.clicked.connect(lambda: self._controller.piece_button_is_clicked(('e', '5', 'v'), self.buttonE5v))
        self.buttonE6h.clicked.connect(lambda: self._controller.piece_button_is_clicked(('e', '6', 'h'), self.buttonE6h))
        self.buttonF1v.clicked.connect(lambda: self._controller.piece_button_is_clicked(('f', '1', 'v'), self.buttonF1v))
        self.buttonF2v.clicked.connect(lambda: self._controller.piece_button_is_clicked(('f', '2', 'v'), self.buttonF2v))
        self.buttonF3v.clicked.connect(lambda: self._controller.piece_button_is_clicked(('f', '3', 'v'), self.buttonF3v))
        self.buttonF4v.clicked.connect(lambda: self._controller.piece_button_is_clicked(('f', '4', 'v'), self.buttonF4v))
        self.buttonF5v.clicked.connect(lambda: self._controller.piece_button_is_clicked(('f', '5', 'v'), self.buttonF5v))

        self.action00.triggered.connect(lambda: self._controller.new_game())

    def set_current_player_color(self, color):
        if (color == Color.red):
            self.currentPlayerLabel.setText("<html><head/><body><p><span style=\" color:#ff0000;\">•</span></p></body></html>")
        else:
            self.currentPlayerLabel.setText("<html><head/><body><p><span style=\" color:#0055ff;\">•</span></p></body></html>")

